### ISSUE TITLE
Update to new 1.7.9-versioned API

### ISSUE THREAD

**Issue by ejm** [JanekOstendorf/AccountsClientPHP#2]
Original AccountsClient now documented, much easier to use, as well.  Check the original repo's wiki page for more.  It also has support for resolution of names from uuid's, which would solve issue #1

**Comment by JanekOstendorf** [comment]
I'm acutally looking for a simpler design at the moment, rather than just porting Mojangs API one to one. But I'm working on it.

**Comment by ejm** [comment]
Ah, sounds good :) I took a similar approach on my Python library
(AccountsClientPython), it is sort of like Mojang's except it is in one
file, and no additional classes (like Profile), it just spits out an array!

**Comment by JanekOstendorf** [comment]
Closed by 63302835dce17c7e64f87d6d47a4478adaf5aa0c
